installers/linux/universal/tar/build.gradle

This PR changes the version string on future builds of Corretto11 for linux to include LTS as the version opt.
Windows and Mac versions of Corretto11 are generated with LTS in the version opt, but we missed it in the Linux build
Generated a new build on Linux:
```
$ bin/java -version
openjdk version "11.0.2" 2019-01-15 LTS
OpenJDK Runtime Environment Corretto-11.0.2.9.1 (build 11.0.2+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.2.9.1 (build 11.0.2+9-LTS, mixed mode)
```
Works on OS: CentOS6
Applies to version: 11.0.2.9.1

Adding LTS as version opt for linux builds.

---

installers/mac/pkg/resources/introduction.html

This commit fixes #10 
Fix the introduction message. The installer title should be "Amazon Corretto 11 Installer".

Fix Corretto 11 mac installer introduction message

---

installers/mac/tar/build.gradle

`Contents/MacOS/libjli.dylib` in Corretto 11 points to the wrong path
causing Mac's java utility tool `/usr/libexec/java_home` unable to
detect amazon-corretto-11.jdk as a JDK package. Fix #12

Fix libjli.dylib symlink error in Corretto 11 installer

---

installers/linux/al2/README.md
installers/linux/al2/docker/Dockerfile
installers/linux/al2/docker/build.gradle
installers/linux/al2/docker/post-install-test.sh
installers/linux/al2/spec/build.gradle
installers/linux/al2/spec/java-11-amazon-corretto.spec.template

Fixes #15, where Amazon Linux asked us to udpate the path in the source tarball that they use.
Additionally, I took this as an opportunity to update the testing Docker file to use the Corretto 11 official image.
Lastly, here's the rendered spec file corresponding to the GA (11.0.2.9.3).
```
#
#
#
%global java_home %{_jvmdir}/%{name}.%{_arch}
%global alternatives_priority 1000
%global __jar_repack 0
%define debug_package %{nil}
%global script 'use File::Spec; print File::Spec->abs2rel($ARGV[0], $ARGV[1])'
%global abs2rel %{__perl} -e %{script}
Summary: Amazon Corretto development environment
Name: java-11-amazon-corretto
Version: 11.0.2+9
Release: 3%{?dist}
Epoch: 1
Group: Development/Languages
AutoReqProv: 0
License: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 …
```

Insert name-version into base path of RPM source tarball.

---

installers/linux/universal/deb/build.gradle
installers/linux/universal/deb/jinfo/jinfo.template

Include jinfo file in deb packaging to support `update-java-alternatives` command.
When packaging deb package, inflate jinfo template and copy it to /usr/lib/jvm/ directory. Make it possible to update Corretto alternatives through update-java-alternatives command.
```
name=java-11-amazon-corretto
alias=java-11-amazon-corretto
priority=11100002
section=main
jdk java /usr/lib/jvm/java-11-amazon-corretto/bin/java
jdk keytool /usr/lib/jvm/java-11-amazon-corretto/bin/keytool
jdk rmid /usr/lib/jvm/java-11-amazon-corretto/bin/rmid
jdk rmiregistry /usr/lib/jvm/java-11-amazon-corretto/bin/rmiregistry
jdk jjs /usr/lib/jvm/java-11-amazon-corretto/bin/jjs
jdk pack200 /usr/lib/jvm/java-11-amazon-corretto/bin/pack200
jdk unpack200 /usr/lib/jvm/java-11-amazon-corretto/bin/unpack200
jdk javac …
```

Add jinfo file to Debian package

---

installers/linux/universal/tar/build.gradle

Fixes #29.
1. Output from listing contents of tar:
```bash
➜  corretto-11 git:(develop) ✗ tar -tvzf installers/linux/universal/tar/corretto-build/distributions/amazon-corretto-11.0.3.7.1-linux-x64.tar.gz | grep cacert
-rw-r--r-- 0/0          183421 2019-06-12 15:50 amazon-corretto-11.0.3.7.1-linux-x64/lib/security/cacerts
```
2. Comparison of our cacerts to the one included in the extracted tar:
```bash
➜  pr sha256sum amazon-corretto-11.0.3.7.1-linux-x64/lib/security/cacerts 
bb471c15a288db084d7b980e22dc59184184d3ba4e700f395cd14bcc1ff7bd68  amazon-corretto-11.0.3.7.1-linux-x64/lib/security/cacerts
➜  corretto-11 git:(develop) ✗ sha256sum cacerts 
bb471c15a288db084d7b980e22dc59184184d3ba4e700f395cd14bcc1ff7bd68  cacerts
```

Don't include OpenJDK's cacerts in Linux's tar distribution.

---

installers/linux/universal/deb/build.gradle
installers/linux/universal/rpm/build.gradle

This is ported from Corretto-8:
* Add support for building rpm package on aarch64 ([28881b6](https://github.com/corretto/corretto-8/commit/28881b6811ec28624eaa47d85fd5f884e526694f))
* Add support for building deb package on aarch64 ([e0a8172](https://github.com/corretto/corretto-8/commit/e0a817207b54cf0c86f78dc03ed7221efd600910))
Test performed in a CentOS7 aarch64 docker:
```
installers/linux/universal/deb/corretto-build/distributions:
total 185004
-rw-r--r-- 1 root root       825 Jun 20 18:20 java-11-amazon-corretto-jdk_11.0.3.7-1_arm64.changes
-rw-r--r-- 1 root root 189438710 Jun 20 18:20 java-11-amazon-corretto-jdk_11.0.3.7-1_arm64.deb
installers/linux/universal/rpm/corretto-build/distributions:
total 185024
-rw-r--r-- 1 root root 189463791 Jun 20 18:17 …
```

Support building rpm and deb on aarch64

---

installers/linux/universal/deb/build.gradle

This commits add provides for both headful and headless runtime for Java 5 to 8 in Corretto-11. This is the 11 port of the PR [corretto-8#199](https://github.com/corretto/corretto-8/pull/199).

corretto-8#190: Add provides for earlier jdks in debian

---

installers/mac/pkg/templates/CorrettoPkg.pkgproj.template
installers/mac/tar/templates/Info.plist.template

Switches hard coded version numbers to variables. This allows for easier portability of code and transitions to new versions.
This will help prevent issues like #10 
This should help with releasing new versions of Corretto as they become available to ensure consistency of version numbers across the macOS packages.
Local builds and installs on macOS Mojave 10.14.6 (18G2022)
Specifically targeting macOS.
If accepted, I will work on porting over to Corretto 8 as well.

Move version numbers to variables

---

.gitignore

Adding a .gitignore to ignore build dirs
Removes unnecessary "untracked files" when working in the git repo.
1. Added `.gitignore`
2. Run `git status`
3. Build directories no long show as untracked files

Inital .gitignore to ignore build dirs

---

installers/mac/pkg/templates/CorrettoPkg.pkgproj.template
installers/mac/tar/templates/Info.plist.template

This update is to properly set version strings in the necessary locations in order to allow for software distribution management software to properly detect the version installed. This is necessary to determine if the version installed requires an update to a newer version.
macOS maintains a database of receipts for installed software. These receipts include package identifiers and installed versions of software. Software distribution management software, such as the open source project [Munki](https://github.com/munki/munki) uses this information to determine what version of the software is currently installed, and to determine if there is a newer version available to upgrade.
Currently, Corretto 11 is always setting this value to `1.0`. …

Updating version strings to recommended formats

---

installers/mac/tar/build.gradle
installers/windows/zip/build.gradle

Mac and Windows build logic would provide the cacerts file before build.
This change will update the logic to merge the cacerts file post build.
Validated that the cacerts file are created as expected.
MacOS and Windows

Update build logic to handle certificates post build

---

src/src/hotspot/share/runtime/globals.hpp

If your issue is specific to Corretto 11,
then you are in the right place.
Please fill in the following information about your pull request.
increase MaxInlineLevel from 9 to 15. 
[PackedIntsDecodeBenchmark.readLongs …

backport of 8234863: Increase default value of MaxInlineLevel

---

installers/linux/universal/tar/build.gradle
installers/mac/pkg/build.gradle
installers/mac/tar/build.gradle

Some Jtreg tests in Corretto 11 requires native libraries. These native libraries are built by the target `test-image-hotspot-jtreg-native`, `test-image-jdk-jtreg-native`, `test-image-hotspot-gtest`. This PR adds Gradle tasks to generate the native libraries as part of the build process on Linux and macOS.
Tests have been performed on Linux & macOS. The target tar `amazon-corretto-testimage-<full_version>-<platform>.tar.gz` was generated correctly.

Add support for test image on Linux and macOS

---

.gitignore
build.gradle
installers/linux/universal/tar/build.gradle
installers/mac/pkg/build.gradle
installers/mac/tar/build.gradle
installers/windows/zip/build.gradle
settings.gradle

This commit fixes the cacert issue reported in corretto-11 #88 
The original gradle task attempts to append Amazon certs to the JDK cacerts under `$JAVA_HOME/lib/security` as a post-build step. In fact, there are two copies of the cert file in `lib/security` and `java.base.jmod` respectively. Patching files in jmod is non-trivial, therefore this commit tries to build the cacerts as a pre-build step. The cacerts file is generated by a new configuration `:prebuild:cacerts`.
This commit has been verified on Windows, Linux (x64) and macOS:
```
$ bin/keytool -list -rfc -cacerts -storepass changeit | grep "Your keystore contains"
Your keystore contains 220 entries
```

Fix missing Amazon cacerts in java.base.jmod

---

build.gradle
installers/linux/universal/deb/build.gradle
installers/linux/universal/rpm/build.gradle
installers/linux/universal/tar/build.gradle
installers/mac/tar/build.gradle
installers/windows/zip/build.gradle

Add two properties to control build behavior:
corretto.debug_level - Control the debug level of the build. Valid
options including: release, fastdebug, debug, slowdebug.
corretto.extra_config - Pass extra configuration flags to the build.
This is the corretto-11 counterpart of [corretto-8#239](https://github.com/corretto/corretto-8/pull/239)
* Linux x86 (slowdebug)
```
./gradlew -Px86=true -Pcorretto.debug_level=debug :installers:linux:universal:deb:build :installers:linux:universal:rpm:build
...
[root@af1061c584ad corretto-11]# ls installers/linux/universal/*/corretto-build/distributions
installers/linux/universal/deb/corretto-build/distributions:
java-11-amazon-corretto-jdk_11.0.7.10-1_i386.changes  java-11-amazon-corretto-jdk_11.0.7.10-1_i386.deb …
```

Support debug build and refactor common gradle logic

---

build.gradle
installers/linux/universal/tar/build.gradle
installers/mac/tar/build.gradle

Utilize `rsync` for incremental build on linux & macOS.
One drawback of extracting the source from the source tar into the build directory is that Make is unable to only incrementally build modified files. This significantly slows down local development.
`rsync` the source from `$root/src` into the build dir also allows the source archiving task and the copy source task to run concurrently. 
On Linux:
```
./gradlew :installers:linux:universal:rpm:build
...
./gradlew :installers:linux:universal:deb:build
<Build artifacts of :installers:linux:universal:tar:build are reused>
```

Use rsync for mac & linux build instead of extracting source from the tgz

---

build.gradle
installers/linux/universal/tar/build.gradle
installers/mac/tar/build.gradle

When introducing the incremental build in corretto-11#106, the license
and legal files are not copied to the buildRoot as expected.
On macOS, Run:
```
./gradlew :installers:mac:tar:copySource
```
* Before the fix
```
$ ls installers/mac/tar/corretto-build/buildRoot
src
$ ls installers/mac/tar/corretto-build/buildRoot/src/corretto-build
distributions
```
* After the fix
```
$ ls installers/mac/tar/corretto-build/buildRoot
ADDITIONAL_LICENSE_INFO LICENSE                 amazon-cacerts          version.txt
ASSEMBLY_EXCEPTION      README.md               src
$ ls installers/mac/tar/corretto-build/buildRoot/src/corretto-build
... No such file or directory
```

Fix license files not included in corretto-11#106

---

src/src/hotspot/share/opto/subnode.cpp
src/test/hotspot/jtreg/compiler/c2/TestBit.java
src/test/micro/org/openjdk/bench/vm/compiler/BitTest.java

From webrev: http://cr.openjdk.java.net/~bulasevich/8247408/webrev.02b/
https://bugs.openjdk.java.net/browse/JDK-8247408

Backport of JDK-8247408 : AARCH64 optimization: using TBZ instruction for bit check

---

src/make/test/JtregNativeJdk.gmk
src/test/jdk/sun/management/jmxremote/bootstrap/GeneratePropertyPassword.sh
src/test/jdk/sun/management/windows/README
src/test/jdk/sun/management/windows/exerevokeall.c

JTreg Tier2 tests on Windows are hitting an infinite loop in revokeall.exe.
Issue was fixed upstream and needed to be backported.
https://bugs.openjdk.java.net/browse/JDK-8220581
https://bugs.openjdk.java.net/browse/JDK-8214545 …

Backport JDK-8214545 from upstream

---

installers/linux/universal/deb/build.gradle
installers/linux/universal/rpm/build.gradle
installers/linux/universal/tar/build.gradle

Legal directory is make from symlinks which don't preserve the file permissions.
Exclude legal from the bulk file copy and add with correct fileMode to ensure
files are not executable or writable.

Set legal directory file permissions.

---

src/src/hotspot/share/opto/callGenerator.cpp
src/src/hotspot/share/opto/castnode.cpp
src/src/hotspot/share/opto/compile.cpp
src/src/hotspot/share/opto/compile.hpp

Reviewed-by: roland, shade
https://bugs.openjdk.java.net/browse/JDK-8059241
http://hg.openjdk.java.net/jdk/jdk/rev/47a8fdf84424
If your issue is specific to Corretto 11,
then you are in the right place.
Please fill in the …

8059241: C2: Excessive RemoveUseless passes during incremental inlining

---

src/src/hotspot/share/classfile/javaClasses.cpp
src/src/hotspot/share/classfile/javaClasses.hpp
src/src/hotspot/share/prims/unsafe.cpp
src/src/java.base/share/classes/java/lang/Thread.java

Reviewed-by: dcubed, rehn
https://bugs.openjdk.java.net/browse/JDK-8222518
http://hg.openjdk.java.net/jdk/jdk/rev/9ebb614d293d
Applies cleanly
If your issue is specific to Corretto 11,
then you are in the right place.
Please …

8222518: Remove unnecessary caching of Parker object in java.lang.Thread

---

src/src/java.base/share/classes/java/util/zip/InflaterOutputStream.java
src/test/jdk/java/util/zip/DeflateIn_InflateOut.java
src/test/micro/org/openjdk/bench/java/util/zip/Streams.java

Reviewed-by: stuefe, vtewari, redestad, lancea
https://bugs.openjdk.java.net/browse/JDK-8242848
https://hg.openjdk.java.net/jdk/jdk/rev/0a45e02c7b77
Applies cleanly
If your issue is specific to Corretto 11,
then you are in the …

8242848: Improve performance of InflaterOutputStream.write()
